### ISSUE TITLE
Call to undefined method Contao\System::getContainer() 

### ISSUE THREAD

**Issue by bytehead** [terminal42/contao-easy_themes#46]
```
Fatal error: Uncaught exception Error with message Call to undefined method Contao\System::getContainer() thrown in composer/vendor/terminal42/contao-easy_themes/EasyThemes.php on line 167
#0 composer/vendor/terminal42/contao-easy_themes/EasyThemes.php(82): EasyThemes->prepareBackendNavigationArray(false)
#1 composer/vendor/terminal42/contao-easy_themes/EasyThemes.php(59): EasyThemes->generateContainerContent()
#2 system/modules/core/classes/BackendTemplate.php(42): EasyThemes->addContainer('...', 'be_main')
#3 system/modules/core/classes/BackendTemplate.php(110): Contao\BackendTemplate->parse()
#4 system/modules/core/controllers/BackendMain.php(275): Contao\BackendTemplate->output()
#5 system/modules/core/controllers/BackendMain.php(135): Contao\BackendMain->output()
#6 contao/main.php(20): Contao\BackendMain->run()
#7 {main}
```

Contao: 3.5.40
easy_themes: 2.2.10.
PHP: 7.2

Introduced with this commit: 0744a4a1fa51a5f3027ee558c4bc7fb5f5ba81de.

**Comment by qzminski** [comment]
Please downgrade to 2.2.9 if possible. Meanwhile I will check with @Toflar how to solve that problem best.

**Comment by Toflar** [comment]
What's the issue here? 3.5 is not supported anymore?

**Comment by bytehead** [comment]
I know, but 2.2.10 is still installable but shouldn't with Contao 3.5 (the minimum version raise was in 2.2.11).

**Comment by Toflar** [comment]
Yeah, that's a bug we cannot fix.

**Comment by qzminski** [comment]
How about a force push?

**Comment by Toflar** [comment]
we can just delete the tag.

**Comment by qzminski** [comment]
I've just deleted 2.2.10 :+1: @bytehead can you confirm it no longer updates to that version? 🙄

**Comment by bytehead** [comment]
Thank you, works! :)
